//! `reconcile()` — master plan §4.8.
//!
//! Every verdict here is produced from a **hand-constructed git state**: a real
//! clone, mutated the way the thing being modelled would mutate it, then
//! observed and classified. Asserting the classifier against structs it was
//! written alongside would prove only that the author was self-consistent.

mod common;

use std::path::Path;

use conductor_core::{PolicyHash, RunId, TaskId};
use conductor_git::baseline::observe;
use conductor_git::clone::{WorkspaceRequest, create_workspace};
use conductor_git::reconcile::{
    AgentReport, FindingKind, ReportClaim, Scope, SensitivePatterns, Verdict, VerificationOutcome,
    reconcile,
};

use common::{clean_repo, git, git_out, write};

struct Run {
    _source: common::Fixture,
    _root: tempfile::TempDir,
    ws: conductor_git::Workspace,
}

impl Run {
    fn path(&self) -> &Path {
        &self.ws.path
    }
}

/// A workspace cloned from a clean source at its HEAD.
fn run() -> Run {
    let source = clean_repo();
    let root = tempfile::tempdir().expect("tempdir");
    let path = root.path().join("run");
    let head = git_out(source.path(), &["rev-parse", "HEAD"]);
    let ws = create_workspace(&WorkspaceRequest {
        source: source.path().to_path_buf(),
        workspace: path,
        run_id: RunId::new("r-0041").expect("valid"),
        task_id: TaskId::new("T-0012").expect("valid"),
        base_commit: head,
        policy_hash: PolicyHash::new("blake3:deadbeef").expect("valid"),
    })
    .expect("create");
    Run {
        _source: source,
        _root: root,
        ws,
    }
}

/// Observe and classify with everything in scope and no report.
fn classify(run: &Run, scope: &[&str]) -> conductor_git::reconcile::Reconciliation {
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");
    reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(scope.iter().map(|s| (*s).to_string())),
        &SensitivePatterns::default(),
        None,
        None,
    )
}

#[test]
fn nothing_happened_is_no_change() {
    let run = run();
    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::NoChange, "{result:?}");
    assert!(result.findings().is_empty(), "{:?}", result.findings());
}

#[test]
fn in_scope_changes_with_no_report_are_clean_no_report() {
    // Acceptance row 3/4: a report is not required for correctness.
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");

    let result = classify(&run, &["src/**"]);
    assert_eq!(result.verdict, Verdict::CleanNoReport, "{result:?}");
}

#[test]
fn in_scope_changes_with_a_consistent_report_are_clean_complete() {
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");

    let report = AgentReport {
        claim: ReportClaim::Complete,
        files_touched: vec!["src/lib.rs".to_string()],
    };
    let result = reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(["src/**".to_string()]),
        &SensitivePatterns::default(),
        Some(&report),
        None,
    );

    assert_eq!(result.verdict, Verdict::CleanComplete, "{result:?}");
    assert!(result.findings().is_empty(), "{:?}", result.findings());
}

#[test]
fn committed_in_scope_changes_are_seen_as_changes() {
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");
    git(run.path(), &["add", "-A"]);
    git(run.path(), &["commit", "-q", "-m", "agent work"]);

    let result = classify(&run, &["src/**"]);
    assert_eq!(result.verdict, Verdict::CleanNoReport, "{result:?}");
}

#[test]
fn a_change_outside_the_declared_scope_is_out_of_scope() {
    let run = run();
    write(run.path(), "docs/notes.md", "the agent edited the docs\n");

    let result = classify(&run, &["src/**"]);
    assert_eq!(result.verdict, Verdict::OutOfScope, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::OutOfScopePath
                && f.path.as_deref() == Some("docs/notes.md")),
        "{:?}",
        result.findings()
    );
}

#[test]
fn touching_a_lockfile_is_policy_sensitive_even_when_it_is_in_scope() {
    let run = run();
    write(run.path(), "Cargo.lock", "# regenerated by the agent\n");

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::PolicySensitivePath),
        "{:?}",
        result.findings()
    );
}

#[test]
fn touching_a_migration_is_policy_sensitive() {
    let run = run();
    write(
        run.path(),
        "db/migrations/0002_add_column.sql",
        "ALTER TABLE t ADD c INT;\n",
    );

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
}

#[test]
fn a_remote_added_inside_the_clone_is_policy_sensitive_even_with_an_identical_tree() {
    // Acceptance row 14. The tree never changes, so a classifier that keyed only
    // on the tree would return NO_CHANGE and the mutation would vanish. This is
    // the reason `NO_CHANGE` is checked *after* the structural deltas.
    let run = run();
    git(
        run.path(),
        &["remote", "add", "evil", "https://example.invalid/x.git"],
    );

    let result = classify(&run, &["**"]);

    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::RemoteChanged),
        "{:?}",
        result.findings()
    );
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::ConfigChanged),
        "a remote is config; both diffs must see it: {:?}",
        result.findings()
    );
}

#[test]
fn rewriting_the_committer_identity_is_policy_sensitive() {
    let run = run();
    git(run.path(), &["config", "user.email", "someone@else"]);

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
}

#[test]
fn deleting_a_branch_inside_the_clone_raises_a_ref_finding() {
    let run = run();
    git(run.path(), &["branch", "-D", "main"]);

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::RefRemoved
                && f.path.as_deref() == Some("refs/heads/main")),
        "{:?}",
        result.findings()
    );
}

#[test]
fn the_run_branch_advancing_is_not_a_ref_finding() {
    // Committing on the run branch is the whole point of the run. A ref diff
    // that flagged it would make every successful run look like an attack.
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");
    git(run.path(), &["add", "-A"]);
    git(run.path(), &["commit", "-q", "-m", "agent work"]);

    let result = classify(&run, &["src/**"]);
    assert!(
        !result
            .findings()
            .iter()
            .any(|f| matches!(f.kind, FindingKind::RefChanged | FindingKind::RefRemoved)),
        "{:?}",
        result.findings()
    );
}

#[test]
fn writing_a_hook_raises_a_finding() {
    let run = run();
    std::fs::write(
        run.path().join(".git/hooks/pre-commit"),
        "#!/bin/sh\nexfiltrate\n",
    )
    .expect("write hook");

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::HookAdded),
        "{:?}",
        result.findings()
    );
}

#[test]
fn stashing_raises_a_finding() {
    let run = run();
    write(run.path(), "src/lib.rs", "edited then hidden\n");
    git(run.path(), &["stash", "push", "-q"]);

    let result = classify(&run, &["**"]);
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::StashChanged),
        "{:?}",
        result.findings()
    );
}

#[test]
fn a_report_claiming_success_over_an_untouched_tree_is_contradicted() {
    // Acceptance row 6. Git wins.
    let run = run();
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");
    let report = AgentReport {
        claim: ReportClaim::Complete,
        files_touched: Vec::new(),
    };

    let result = reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(["**".to_string()]),
        &SensitivePatterns::default(),
        Some(&report),
        None,
    );

    assert_eq!(result.verdict, Verdict::Contradicted, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::ReportContradicted),
        "{:?}",
        result.findings()
    );
}

#[test]
fn a_report_naming_a_file_git_never_saw_change_is_contradicted() {
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");
    let report = AgentReport {
        claim: ReportClaim::Complete,
        files_touched: vec!["src/lib.rs".to_string(), "src/ghost.rs".to_string()],
    };

    let result = reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(["src/**".to_string()]),
        &SensitivePatterns::default(),
        Some(&report),
        None,
    );

    assert_eq!(result.verdict, Verdict::Contradicted, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::ReportContradicted
                && f.path.as_deref() == Some("src/ghost.rs")),
        "{:?}",
        result.findings()
    );
}

#[test]
fn an_observed_change_the_report_does_not_mention_raises_a_finding_without_changing_the_verdict() {
    // §4.8: "Any unexplained delta raises a Finding." Under-reporting is a
    // delta the report does not explain; it is not a contradiction, because
    // nothing the report asserted turned out to be false.
    let run = run();
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");
    write(run.path(), "src/two.rs", "pub fn two() -> u32 { 22 }\n");
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");
    let report = AgentReport {
        claim: ReportClaim::Complete,
        files_touched: vec!["src/lib.rs".to_string()],
    };

    let result = reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(["src/**".to_string()]),
        &SensitivePatterns::default(),
        Some(&report),
        None,
    );

    assert_eq!(result.verdict, Verdict::CleanComplete, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::ReportOmittedChange
                && f.path.as_deref() == Some("src/two.rs")),
        "{:?}",
        result.findings()
    );
}

#[test]
fn a_merge_in_progress_is_corrupt() {
    let run = run();
    std::fs::write(run.path().join(".git/MERGE_HEAD"), "deadbeef\n").expect("write");

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::Corrupt, "{result:?}");
}

#[test]
fn a_damaged_object_store_is_corrupt() {
    // Acceptance row 15's clone-side half: the workspace is damaged. The
    // source-side half — that the damage stops at the clone — is isolation.rs.
    let run = run();
    let objects = common::loose_object_files(run.path());
    let victim = objects
        .first()
        .expect("the workspace has loose objects")
        .clone();
    corrupt_in_place(&victim);

    let result = classify(&run, &["**"]);
    assert_eq!(result.verdict, Verdict::Corrupt, "{result:?}");
    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::RepositoryCorrupt),
        "{:?}",
        result.findings()
    );
}

#[test]
fn corrupt_outranks_every_other_verdict() {
    // A repository that cannot be read cannot be classified. Anything else
    // would be reporting a conclusion drawn from evidence known to be unusable.
    let run = run();
    write(run.path(), "docs/notes.md", "out of scope edit\n");
    write(run.path(), "Cargo.lock", "sensitive edit\n");
    git(
        run.path(),
        &["remote", "add", "evil", "https://example.invalid/x.git"],
    );
    std::fs::write(run.path().join(".git/MERGE_HEAD"), "deadbeef\n").expect("write");

    let result = classify(&run, &["src/**"]);
    assert_eq!(result.verdict, Verdict::Corrupt, "{result:?}");
}

#[test]
fn a_passing_verification_does_not_soften_a_policy_sensitive_verdict() {
    // Acceptance row 24: policy wins over green tests.
    let run = run();
    write(run.path(), "Cargo.lock", "# regenerated by the agent\n");
    let observed = observe(run.path(), &run.ws.baseline).expect("observe");

    let result = reconcile(
        &run.ws.baseline,
        &observed,
        &Scope::new(["**".to_string()]),
        &SensitivePatterns::default(),
        None,
        Some(VerificationOutcome::Pass),
    );

    assert_eq!(result.verdict, Verdict::PolicySensitive, "{result:?}");
    assert_eq!(result.verification, Some(VerificationOutcome::Pass));
}

#[test]
fn a_modified_nested_repository_raises_a_finding_and_is_excluded_from_scope_checks() {
    // §4.1: nested repositories are "detected at baseline, excluded from scope
    // checks, and raise a finding if modified".
    let run = run();
    let nested = run.path().join("vendor/nested");
    std::fs::create_dir_all(&nested).expect("create");
    git(&nested, &["init", "-q", "-b", "main"]);
    write(&nested, "inner.txt", "one\n");
    git(&nested, &["add", "-A"]);
    git(&nested, &["commit", "-q", "-m", "nested one"]);

    // Re-baseline: this is the state the run would have started from.
    let baseline = conductor_git::capture_baseline(run.path()).expect("capture");
    assert!(
        !baseline.nested_repos.is_empty(),
        "fixture must have a nested repo"
    );

    write(&nested, "inner.txt", "two\n");
    git(&nested, &["add", "-A"]);
    git(&nested, &["commit", "-q", "-m", "nested two"]);
    write(run.path(), "src/lib.rs", "pub fn one() -> u32 { 11 }\n");

    let observed = observe(run.path(), &baseline).expect("observe");
    let result = reconcile(
        &baseline,
        &observed,
        &Scope::new(["src/**".to_string()]),
        &SensitivePatterns::default(),
        None,
        None,
    );

    assert!(
        result
            .findings()
            .iter()
            .any(|f| f.kind == FindingKind::NestedRepoModified),
        "{:?}",
        result.findings()
    );
    assert_eq!(
        result.verdict,
        Verdict::CleanNoReport,
        "the nested repo is outside `src/**` but must not be scope-checked: {result:?}"
    );
}

#[test]
fn classification_needs_no_repository_at_all() {
    // §2.1's whole reason for splitting observation from classification: the
    // pure half must be exhaustively testable without a runtime. If this
    // compiles and runs, `reconcile` touched no filesystem, because it was
    // handed data that never came from one.
    let baseline = conductor_git::Baseline {
        base_commit: "a".repeat(40),
        tree_hash: "b".repeat(40),
        head_branch: Some("conductor/T-1/r-1".to_string()),
        status: Vec::new(),
        untracked: Vec::new(),
        config: Default::default(),
        remotes: Default::default(),
        refs: Default::default(),
        submodules: Vec::new(),
        stash_count: 0,
        hooks: Default::default(),
        nested_repos: Vec::new(),
    };
    let observed = conductor_git::Observed {
        repo: baseline.clone(),
        health: conductor_git::RepoHealth {
            workspace_present: true,
            git_dir_readable: true,
            head_resolvable: true,
            detached_head: false,
            merge_in_progress: false,
            rebase_in_progress: false,
            cherry_pick_in_progress: false,
            revert_in_progress: false,
            bisect_in_progress: false,
            index_lock_present: false,
            object_store_ok: true,
            notes: Vec::new(),
        },
        new_commits: Vec::new(),
        committed_changes: Vec::new(),
        staged: Vec::new(),
        unstaged: Vec::new(),
        reflog: Vec::new(),
    };

    let result = reconcile(
        &baseline,
        &observed,
        &Scope::new(["**".to_string()]),
        &SensitivePatterns::default(),
        None,
        None,
    );
    assert_eq!(result.verdict, Verdict::NoChange);
}

/// Flip bytes in the middle of a file without changing its length, after making
/// it writable. Object files are `-r--r--r--`, but the same user owns them.
fn corrupt_in_place(path: &Path) {
    use std::io::{Seek, SeekFrom, Write};
    use std::os::unix::fs::PermissionsExt;

    let mut perms = std::fs::metadata(path).expect("stat").permissions();
    perms.set_mode(perms.mode() | 0o200);
    std::fs::set_permissions(path, perms).expect("chmod u+w");

    let len = std::fs::metadata(path).expect("stat").len();
    let offset = (len / 2).max(2);
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .open(path)
        .expect("open for writing");
    file.seek(SeekFrom::Start(offset)).expect("seek");
    file.write_all(&[0x00, 0xff, 0x00, 0xff]).expect("write");
    file.flush().expect("flush");
}
