//! State enums for the `TEXT` state columns the store persists.
//!
//! Sources: master plan §5.2 (state machines) and Part 5.1 (column comments).
//! Transition rules are **not** here — they are S3/S5. This module only decides
//! which strings are legal in which column, and how they map to Rust.

use serde::Serialize;

/// A state column held a string that is not a member of its enum.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{type_name} has no variant {value:?}")]
pub struct ParseStateError {
    /// The enum that rejected the value.
    pub type_name: &'static str,
    /// The rejected value.
    pub value: String,
}

macro_rules! state_enum {
    (
        $(#[$meta:meta])*
        $name:ident { $( $variant:ident => $text:literal ),+ $(,)? }
        terminal: [ $( $terminal:ident ),* $(,)? ]
    ) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash,
            ::serde::Serialize, ::serde::Deserialize,
        )]
        #[serde(rename_all = "SCREAMING_SNAKE_CASE")]
        pub enum $name {
            $(
                #[doc = concat!("`", $text, "`")]
                $variant,
            )+
        }

        impl $name {
            /// Every variant, in declaration order.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The exact string persisted in the database.
            pub fn as_str(&self) -> &'static str {
                match self {
                    $( $name::$variant => $text ),+
                }
            }

            /// Terminal states, per master plan §5.2.
            pub fn is_terminal(&self) -> bool {
                // A `match` rather than `matches!` so that an empty terminal set
                // is expressible: some of these enums (side-effect kinds) have
                // no terminal member at all.
                #[allow(unreachable_patterns)]
                match self {
                    $( $name::$terminal => true, )*
                    _ => false,
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = $crate::state::ParseStateError;

            fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
                match s {
                    $( $text => Ok($name::$variant), )+
                    other => Err($crate::state::ParseStateError {
                        type_name: stringify!($name),
                        value: other.to_string(),
                    }),
                }
            }
        }
    };
}

// `attempt::AttemptState` is generated by the same macro, so the two encodings
// of a state — the database's and serde's — stay identical for every enum in
// the crate rather than only the ones declared in this file.
pub(crate) use state_enum;

state_enum! {
    /// `task.state` — master plan §5.2, "Task (12 states)".
    TaskState {
        Pending => "PENDING",
        Ready => "READY",
        Running => "RUNNING",
        Reconciling => "RECONCILING",
        AwaitingApproval => "AWAITING_APPROVAL",
        Verifying => "VERIFYING",
        Blocked => "BLOCKED",
        AwaitingReview => "AWAITING_REVIEW",
        Repairing => "REPAIRING",
        Complete => "COMPLETE",
        Cancelled => "CANCELLED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Complete, Cancelled, Superseded]
}

state_enum! {
    /// `run.state`.
    ///
    /// §5.2: the run state "mirrors its task", so this is variant-for-variant
    /// identical to [`TaskState`] and a test in this module holds it that way.
    /// It stays a separate type because it is a separate column: a run and its
    /// task are written by different statements and can legally disagree for
    /// the duration of a transaction.
    ///
    /// **`RECOVERING` is deliberately absent (S3).** §4.7's claim predicate said
    /// `state IN ('READY','RECOVERING')` while §5.2's machine has no such state,
    /// so half the claim could never match. S1 shipped the statement verbatim
    /// rather than guess. S3 resolved it in favour of §5.2: §5.2's restart rule
    /// forces a crashed run to `RECONCILING`, lease expiry is what produces a
    /// reclaimable run, and `RECONCILING` is therefore the state the claim must
    /// select. A variant nothing can write is a dead disjunct, and a dead
    /// disjunct in a safety-critical predicate is worse than no disjunct: it
    /// reads as coverage.
    ///
    /// The terminal set is fixed by the partial index
    /// `ix_run_one_active_per_task ... WHERE state NOT IN
    /// ('COMPLETE','CANCELLED','SUPERSEDED')`.
    RunState {
        Pending => "PENDING",
        Ready => "READY",
        Running => "RUNNING",
        Reconciling => "RECONCILING",
        AwaitingApproval => "AWAITING_APPROVAL",
        Verifying => "VERIFYING",
        Blocked => "BLOCKED",
        AwaitingReview => "AWAITING_REVIEW",
        Repairing => "REPAIRING",
        Complete => "COMPLETE",
        Cancelled => "CANCELLED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Complete, Cancelled, Superseded]
}

state_enum! {
    /// `plan_version.state` — Part 5.1 column comment and §5.2 "Plan (5 states)".
    PlanVersionState {
        Draft => "DRAFT",
        Validated => "VALIDATED",
        AwaitingApproval => "AWAITING_APPROVAL",
        Approved => "APPROVED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Superseded]
}

state_enum! {
    /// `review.state` — §5.2 *"Review (3 states)"*.
    ///
    /// ```text
    /// PENDING ─export─► EXPORTED ─import─► DECIDED
    /// ```
    ///
    /// Transition rules live in [`crate::review`], for the same reason
    /// [`TaskState`]'s live in [`crate::task`]: this module decides which strings
    /// are legal in which column, and nothing else.
    ///
    /// `DECIDED` is terminal, and that is load-bearing rather than tidy. §6.5
    /// makes importing a decision *"a **mutating** operation … never a file an
    /// agent could write"*, so the import path is somewhere an attacker would
    /// like to arrive twice — once to have a decision applied and again to have
    /// a different one applied. A terminal `DECIDED` makes the second arrival a
    /// refusal instead of a second answer.
    ReviewState {
        Pending => "PENDING",
        Exported => "EXPORTED",
        Decided => "DECIDED",
    }
    terminal: [Decided]
}

state_enum! {
    /// `attempt.outcome` — Part 5.1 column comment.
    ///
    /// The attempt *state* diagram in §5.2 is not represented here because the
    /// `attempt` table has no `state` column; only `outcome` is persisted.
    AttemptOutcome {
        Exited => "EXITED",
        Crashed => "CRASHED",
        TimedOut => "TIMED_OUT",
        Stale => "STALE",
        Reconciled => "RECONCILED",
    }
    terminal: [Reconciled]
}

impl RunState {
    /// True while the run still occupies its task's single active-run slot,
    /// i.e. exactly the predicate of `ix_run_one_active_per_task`.
    pub fn occupies_active_slot(&self) -> bool {
        !self.is_terminal()
    }

    /// The states a worker may claim (§4.7's claim predicate, as resolved by S3).
    ///
    /// `READY` is fresh work. `RECONCILING` is a run whose worker died: §5.2's
    /// restart rule forces such a run to `RECONCILING`, and a `RECONCILING` run
    /// whose lease has expired is exactly what a restarting worker must take.
    pub const CLAIMABLE: &'static [RunState] = &[RunState::Ready, RunState::Reconciling];

    /// The states §4.7 step 2 sweeps at startup and on the lease tick: a run in
    /// one of these with an expired lease had a worker that is no longer there.
    pub const LEASE_BEARING: &'static [RunState] = &[
        RunState::Running,
        RunState::Reconciling,
        RunState::Verifying,
    ];

    /// The same state, read as its task's.
    ///
    /// §5.2: the run "mirrors its task", and `the_run_state_mirrors_its_task_
    /// variant_for_variant` holds the two enums to the same set. This makes that
    /// mirroring usable rather than merely asserted: §5.2 draws **one** machine,
    /// so there is one legality table
    /// ([`TaskState::transition_to`](crate::TaskState::transition_to)) and the
    /// run's transitions are checked against it. A second table for runs would
    /// be a second thing to keep in agreement, which is exactly the argument
    /// §5.2 gives for not having a separate run state machine at all.
    pub fn as_task_state(&self) -> TaskState {
        match self {
            RunState::Pending => TaskState::Pending,
            RunState::Ready => TaskState::Ready,
            RunState::Running => TaskState::Running,
            RunState::Reconciling => TaskState::Reconciling,
            RunState::AwaitingApproval => TaskState::AwaitingApproval,
            RunState::Verifying => TaskState::Verifying,
            RunState::Blocked => TaskState::Blocked,
            RunState::AwaitingReview => TaskState::AwaitingReview,
            RunState::Repairing => TaskState::Repairing,
            RunState::Complete => TaskState::Complete,
            RunState::Cancelled => TaskState::Cancelled,
            RunState::Superseded => TaskState::Superseded,
        }
    }

    /// The only exit from `RUNNING` (§4.8: "**Every exit from `RUNNING` passes
    /// through it** — success, crash, timeout, cancel").
    ///
    /// This is a function of one argument returning one value, which is the
    /// point: there is no second destination to pass, so `RUNNING → COMPLETE`
    /// is not rejected at runtime — it cannot be expressed. Obtaining the
    /// [`TerminalAttempt`](crate::attempt::TerminalAttempt) it requires is only
    /// possible from an attempt that actually reached a terminal state.
    ///
    /// ```compile_fail
    /// # use conductor_core::RunState;
    /// // There is no evidence-free way to leave RUNNING.
    /// let _ = RunState::leave_running();
    /// ```
    pub fn leave_running(_evidence: &crate::attempt::TerminalAttempt) -> RunState {
        RunState::Reconciling
    }
}

/// Where a run goes after reconciliation.
///
/// **`COMPLETE` cannot be named without evidence, and that is the
/// enforcement.** §5.2 lists "any `→ COMPLETE` without verification bound to
/// the final tree hash" as an invalid transition.
///
/// S3 shipped this enum with **no** `Complete` variant, on the grounds that
/// verification did not exist yet: "until S4 supplies verification, no code
/// path — tested or untested — can route a reconciled run to it." S4 supplies
/// it. The variant therefore appears, but it is **not** a bare variant that any
/// code can construct: it carries a
/// [`VerifiedComplete`](crate::completion::VerifiedComplete), whose fields are
/// private and whose only constructor is
/// [`completion::evaluate`](crate::completion::evaluate). The guarantee is the
/// same shape as [`TerminalAttempt`](crate::attempt::TerminalAttempt): the
/// value is earned, not spoken.
///
/// ```compile_fail
/// # use conductor_core::{ReconciledRoute, completion::VerifiedComplete};
/// // `VerifiedComplete` has no public constructor and no public fields.
/// let _ = ReconciledRoute::Complete(VerifiedComplete { tree_hash: "t".to_string() });
/// ```
///
/// Non-vacuity control: the same shape with a variant that needs no evidence
/// compiles.
///
/// ```
/// # use conductor_core::{ReconciledRoute, RunState};
/// assert_eq!(ReconciledRoute::Verifying.state(), RunState::Verifying);
/// ```
/// **`Deserialize` is deliberately absent**, and so is `Hash`. A route that
/// could be deserialised would let `{"COMPLETE": {"tree_hash": "…"}}` from a
/// file, a socket or a packet mint a `VerifiedComplete` — the exact back door
/// the private constructor exists to close. The type is written out as
/// evidence, never read back in as authority; what is read back is the
/// `run.state` column, which is a [`RunState`] and carries no proof at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ReconciledRoute {
    /// Changes are in scope and explained: run the verification profile.
    Verifying,
    /// A policy-sensitive change needs a decision before anything advances.
    AwaitingApproval,
    /// A human must look: contradiction, out-of-scope change, or a finding.
    AwaitingReview,
    /// The run cannot proceed at all — workspace gone, repository corrupt.
    Blocked,
    /// The attempt did nothing useful and budget remains: try again.
    Repairing,
    /// Every completion criterion S4 owns held at the run's current tree.
    ///
    /// The payload is the proof. It also carries the criteria that were
    /// deferred to a later slice, so a `COMPLETE` reached today is explicit
    /// about what it did not check.
    Complete(crate::completion::VerifiedComplete),
}

/// What a human's review decision writes to `run.state` — §5.2, S13.
///
/// # Why this is not `ReconciledRoute`
///
/// [`ReconciledRoute`] is what *reconciliation* concluded, and it has no
/// `Superseded` or `Cancelled` variant because reconciliation never abandons a
/// task — only a person does. Reusing it would mean adding two variants that no
/// reconciliation can produce, and then every exhaustive `match` in the
/// reconciliation path would gain two arms it must declare unreachable. Two
/// enums, each total over its own domain, is the smaller lie.
///
/// # `Accepted` carries the proof, for the same reason `Complete` does
///
/// This enum writes `RunState::Complete`, which is the state
/// [`ReconciledRoute::Complete`] guards with a
/// [`VerifiedComplete`](crate::completion::VerifiedComplete) that only
/// [`completion::evaluate`](crate::completion::evaluate) can mint. A review edge
/// that wrote the same state without the same token would be the one door into
/// `COMPLETE` needing no evidence — and it would be the door a human is
/// encouraged to walk through. So `Accepted` carries the token, and ADR-0019
/// records why acceptance satisfies criterion 6 without excusing the other six.
///
/// ```compile_fail
/// # use conductor_core::{ReviewOutcome, completion::VerifiedComplete};
/// // `VerifiedComplete` has no public constructor and no public fields.
/// let _ = ReviewOutcome::Accepted(VerifiedComplete { tree_hash: "t".to_string() });
/// ```
///
/// Non-vacuity control: a variant that certifies nothing needs no evidence and
/// compiles.
///
/// ```
/// # use conductor_core::{ReviewOutcome, RunState};
/// assert_eq!(ReviewOutcome::Cancelled.state(), RunState::Cancelled);
/// ```
///
/// **`Deserialize` is deliberately absent**, exactly as it is on
/// [`ReconciledRoute`]: a decision arrives from a file a human edited, and a
/// route that could be deserialised would let `{"ACCEPTED": {...}}` in that file
/// mint a `VerifiedComplete`. What is read out of the human's file is a
/// [`ReviewDecision`](crate::review::ReviewDecision), which carries no proof at
/// all; the proof is earned afterwards, on this side, by running the gate.
///
/// **There is no `Paused` variant.** Pausing writes no state — see
/// [`ReviewDecision::task_target`](crate::review::ReviewDecision::task_target).
/// A variant here would be a state transition for a decision that is
/// deliberately not one, and a self-transition is refused anyway.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ReviewOutcome {
    /// A human accepted the work. The payload is the completion proof.
    Accepted(crate::completion::VerifiedComplete),
    /// Send it back for a bounded repair attempt.
    Repairing,
    /// The plan was wrong; a new version supersedes this task.
    Superseded,
    /// Abandon the task.
    Cancelled,
}

impl ReviewOutcome {
    /// The `run.state` this outcome writes.
    pub fn state(&self) -> RunState {
        match self {
            ReviewOutcome::Accepted(_) => RunState::Complete,
            ReviewOutcome::Repairing => RunState::Repairing,
            ReviewOutcome::Superseded => RunState::Superseded,
            ReviewOutcome::Cancelled => RunState::Cancelled,
        }
    }
}

impl ReconciledRoute {
    /// The `run.state` this route writes.
    pub fn state(&self) -> RunState {
        match self {
            ReconciledRoute::Verifying => RunState::Verifying,
            ReconciledRoute::AwaitingApproval => RunState::AwaitingApproval,
            ReconciledRoute::AwaitingReview => RunState::AwaitingReview,
            ReconciledRoute::Blocked => RunState::Blocked,
            ReconciledRoute::Repairing => RunState::Repairing,
            ReconciledRoute::Complete(_) => RunState::Complete,
        }
    }

    /// Whether this route needs a human before the run can move again (§4.8).
    pub fn requires_human(&self) -> bool {
        matches!(
            self,
            ReconciledRoute::AwaitingApproval
                | ReconciledRoute::AwaitingReview
                | ReconciledRoute::Blocked
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_state_has_twelve_variants() {
        assert_eq!(TaskState::ALL.len(), 12);
    }

    #[test]
    fn run_state_covers_the_claim_predicate() {
        // S1 asserted RECOVERING here, pinning the contradiction §4.7 recorded.
        // S3 resolved it: the claim selects READY and RECONCILING, and every
        // member of the predicate must be a state something can actually write.
        assert_eq!(RunState::Ready.as_str(), "READY");
        assert_eq!(RunState::Reconciling.as_str(), "RECONCILING");
        assert_eq!(RunState::Running.as_str(), "RUNNING");
        assert_eq!(
            RunState::CLAIMABLE,
            &[RunState::Ready, RunState::Reconciling]
        );
    }

    #[test]
    fn recovering_is_not_a_run_state() {
        // The dead disjunct is gone, and it must stay gone: parsing it is an
        // error rather than a silently accepted legacy value.
        assert!("RECOVERING".parse::<RunState>().is_err());
        assert!(!RunState::ALL.iter().any(|s| s.as_str() == "RECOVERING"));
    }

    #[test]
    fn the_run_state_mirrors_its_task_variant_for_variant() {
        // §5.2: "Deliberately thin — mirrors its task." Two enums that are meant
        // to be the same set are two things that can drift, so the agreement is
        // asserted rather than assumed.
        let run: Vec<&str> = RunState::ALL.iter().map(|s| s.as_str()).collect();
        let task: Vec<&str> = TaskState::ALL.iter().map(|s| s.as_str()).collect();
        assert_eq!(run, task);
    }

    #[test]
    fn complete_is_the_only_route_that_reaches_a_terminal_state() {
        // S3's version of this test asserted that *no* route was terminal,
        // because the type had no `Complete` variant at all. S4 adds one, and
        // the property that replaces it is narrower and still load-bearing:
        // every evidence-free route is non-terminal, and the single terminal
        // route is the one whose payload cannot be constructed without the
        // gate. `tests/completion.rs` pins the gate itself.
        for route in [
            ReconciledRoute::Verifying,
            ReconciledRoute::AwaitingApproval,
            ReconciledRoute::AwaitingReview,
            ReconciledRoute::Blocked,
            ReconciledRoute::Repairing,
        ] {
            assert!(
                !route.state().is_terminal(),
                "{route:?} routes to a terminal state"
            );
        }
    }

    #[test]
    fn text_round_trips_for_every_variant() {
        for s in TaskState::ALL {
            assert_eq!(&s.as_str().parse::<TaskState>().expect("parse"), s);
        }
        for s in RunState::ALL {
            assert_eq!(&s.as_str().parse::<RunState>().expect("parse"), s);
        }
        for s in PlanVersionState::ALL {
            assert_eq!(&s.as_str().parse::<PlanVersionState>().expect("parse"), s);
        }
        for s in AttemptOutcome::ALL {
            assert_eq!(&s.as_str().parse::<AttemptOutcome>().expect("parse"), s);
        }
    }

    #[test]
    fn serde_agrees_with_the_persisted_text() {
        // Two encodings of the same thing must not be allowed to drift: the
        // database sees as_str(), a JSON packet sees serde.
        for s in RunState::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
        for s in TaskState::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
        for s in AttemptOutcome::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
    }

    #[test]
    fn unknown_state_is_rejected_not_defaulted() {
        let err = "NOT_A_STATE".parse::<RunState>().unwrap_err();
        assert_eq!(err.type_name, "RunState");
        assert_eq!(err.value, "NOT_A_STATE");
    }

    #[test]
    fn terminal_sets_match_the_partial_index_predicate() {
        let terminal: Vec<&str> = RunState::ALL
            .iter()
            .filter(|s| s.is_terminal())
            .map(|s| s.as_str())
            .collect();
        assert_eq!(terminal, vec!["COMPLETE", "CANCELLED", "SUPERSEDED"]);
        assert!(RunState::Running.occupies_active_slot());
        assert!(!RunState::Complete.occupies_active_slot());
    }
}
