//! State enums for the `TEXT` state columns the store persists.
//!
//! Sources: master plan §5.2 (state machines) and Part 5.1 (column comments).
//! Transition rules are **not** here — they are S3/S5. This module only decides
//! which strings are legal in which column, and how they map to Rust.

use serde::{Deserialize, Serialize};

/// A state column held a string that is not a member of its enum.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{type_name} has no variant {value:?}")]
pub struct ParseStateError {
    /// The enum that rejected the value.
    pub type_name: &'static str,
    /// The rejected value.
    pub value: String,
}

macro_rules! state_enum {
    (
        $(#[$meta:meta])*
        $name:ident { $( $variant:ident => $text:literal ),+ $(,)? }
        terminal: [ $( $terminal:ident ),* $(,)? ]
    ) => {
        $(#[$meta])*
        #[derive(
            Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash,
            ::serde::Serialize, ::serde::Deserialize,
        )]
        #[serde(rename_all = "SCREAMING_SNAKE_CASE")]
        pub enum $name {
            $(
                #[doc = concat!("`", $text, "`")]
                $variant,
            )+
        }

        impl $name {
            /// Every variant, in declaration order.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The exact string persisted in the database.
            pub fn as_str(&self) -> &'static str {
                match self {
                    $( $name::$variant => $text ),+
                }
            }

            /// Terminal states, per master plan §5.2.
            pub fn is_terminal(&self) -> bool {
                // A `match` rather than `matches!` so that an empty terminal set
                // is expressible: some of these enums (side-effect kinds) have
                // no terminal member at all.
                #[allow(unreachable_patterns)]
                match self {
                    $( $name::$terminal => true, )*
                    _ => false,
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = $crate::state::ParseStateError;

            fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
                match s {
                    $( $text => Ok($name::$variant), )+
                    other => Err($crate::state::ParseStateError {
                        type_name: stringify!($name),
                        value: other.to_string(),
                    }),
                }
            }
        }
    };
}

// `attempt::AttemptState` is generated by the same macro, so the two encodings
// of a state — the database's and serde's — stay identical for every enum in
// the crate rather than only the ones declared in this file.
pub(crate) use state_enum;

state_enum! {
    /// `task.state` — master plan §5.2, "Task (12 states)".
    TaskState {
        Pending => "PENDING",
        Ready => "READY",
        Running => "RUNNING",
        Reconciling => "RECONCILING",
        AwaitingApproval => "AWAITING_APPROVAL",
        Verifying => "VERIFYING",
        Blocked => "BLOCKED",
        AwaitingReview => "AWAITING_REVIEW",
        Repairing => "REPAIRING",
        Complete => "COMPLETE",
        Cancelled => "CANCELLED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Complete, Cancelled, Superseded]
}

state_enum! {
    /// `run.state`.
    ///
    /// §5.2: the run state "mirrors its task", so this is variant-for-variant
    /// identical to [`TaskState`] and a test in this module holds it that way.
    /// It stays a separate type because it is a separate column: a run and its
    /// task are written by different statements and can legally disagree for
    /// the duration of a transaction.
    ///
    /// **`RECOVERING` is deliberately absent (S3).** §4.7's claim predicate said
    /// `state IN ('READY','RECOVERING')` while §5.2's machine has no such state,
    /// so half the claim could never match. S1 shipped the statement verbatim
    /// rather than guess. S3 resolved it in favour of §5.2: §5.2's restart rule
    /// forces a crashed run to `RECONCILING`, lease expiry is what produces a
    /// reclaimable run, and `RECONCILING` is therefore the state the claim must
    /// select. A variant nothing can write is a dead disjunct, and a dead
    /// disjunct in a safety-critical predicate is worse than no disjunct: it
    /// reads as coverage.
    ///
    /// The terminal set is fixed by the partial index
    /// `ix_run_one_active_per_task ... WHERE state NOT IN
    /// ('COMPLETE','CANCELLED','SUPERSEDED')`.
    RunState {
        Pending => "PENDING",
        Ready => "READY",
        Running => "RUNNING",
        Reconciling => "RECONCILING",
        AwaitingApproval => "AWAITING_APPROVAL",
        Verifying => "VERIFYING",
        Blocked => "BLOCKED",
        AwaitingReview => "AWAITING_REVIEW",
        Repairing => "REPAIRING",
        Complete => "COMPLETE",
        Cancelled => "CANCELLED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Complete, Cancelled, Superseded]
}

state_enum! {
    /// `plan_version.state` — Part 5.1 column comment and §5.2 "Plan (5 states)".
    PlanVersionState {
        Draft => "DRAFT",
        Validated => "VALIDATED",
        AwaitingApproval => "AWAITING_APPROVAL",
        Approved => "APPROVED",
        Superseded => "SUPERSEDED",
    }
    terminal: [Superseded]
}

state_enum! {
    /// `attempt.outcome` — Part 5.1 column comment.
    ///
    /// The attempt *state* diagram in §5.2 is not represented here because the
    /// `attempt` table has no `state` column; only `outcome` is persisted.
    AttemptOutcome {
        Exited => "EXITED",
        Crashed => "CRASHED",
        TimedOut => "TIMED_OUT",
        Stale => "STALE",
        Reconciled => "RECONCILED",
    }
    terminal: [Reconciled]
}

impl RunState {
    /// True while the run still occupies its task's single active-run slot,
    /// i.e. exactly the predicate of `ix_run_one_active_per_task`.
    pub fn occupies_active_slot(&self) -> bool {
        !self.is_terminal()
    }

    /// The states a worker may claim (§4.7's claim predicate, as resolved by S3).
    ///
    /// `READY` is fresh work. `RECONCILING` is a run whose worker died: §5.2's
    /// restart rule forces such a run to `RECONCILING`, and a `RECONCILING` run
    /// whose lease has expired is exactly what a restarting worker must take.
    pub const CLAIMABLE: &'static [RunState] = &[RunState::Ready, RunState::Reconciling];

    /// The states §4.7 step 2 sweeps at startup and on the lease tick: a run in
    /// one of these with an expired lease had a worker that is no longer there.
    pub const LEASE_BEARING: &'static [RunState] = &[
        RunState::Running,
        RunState::Reconciling,
        RunState::Verifying,
    ];

    /// The only exit from `RUNNING` (§4.8: "**Every exit from `RUNNING` passes
    /// through it** — success, crash, timeout, cancel").
    ///
    /// This is a function of one argument returning one value, which is the
    /// point: there is no second destination to pass, so `RUNNING → COMPLETE`
    /// is not rejected at runtime — it cannot be expressed. Obtaining the
    /// [`TerminalAttempt`](crate::attempt::TerminalAttempt) it requires is only
    /// possible from an attempt that actually reached a terminal state.
    ///
    /// ```compile_fail
    /// # use conductor_core::RunState;
    /// // There is no evidence-free way to leave RUNNING.
    /// let _ = RunState::leave_running();
    /// ```
    pub fn leave_running(_evidence: &crate::attempt::TerminalAttempt) -> RunState {
        RunState::Reconciling
    }
}

/// Where a run goes after reconciliation.
///
/// **`COMPLETE` is not a variant, and that is the enforcement.** §5.2 lists
/// "any `→ COMPLETE` without verification bound to the final tree hash" as an
/// invalid transition; verification is S4. Until S4 exists there is no value of
/// this type that names `COMPLETE`, so no code path — tested or untested — can
/// route a reconciled run to it.
///
/// ```compile_fail
/// # use conductor_core::ReconciledRoute;
/// let _ = ReconciledRoute::Complete;
/// ```
///
/// Non-vacuity control: the same shape with a variant that does exist compiles.
///
/// ```
/// # use conductor_core::{ReconciledRoute, RunState};
/// assert_eq!(ReconciledRoute::Verifying.state(), RunState::Verifying);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ReconciledRoute {
    /// Changes are in scope and explained: run the verification profile.
    Verifying,
    /// A policy-sensitive change needs a decision before anything advances.
    AwaitingApproval,
    /// A human must look: contradiction, out-of-scope change, or a finding.
    AwaitingReview,
    /// The run cannot proceed at all — workspace gone, repository corrupt.
    Blocked,
    /// The attempt did nothing useful and budget remains: try again.
    Repairing,
}

impl ReconciledRoute {
    /// The `run.state` this route writes.
    pub fn state(&self) -> RunState {
        match self {
            ReconciledRoute::Verifying => RunState::Verifying,
            ReconciledRoute::AwaitingApproval => RunState::AwaitingApproval,
            ReconciledRoute::AwaitingReview => RunState::AwaitingReview,
            ReconciledRoute::Blocked => RunState::Blocked,
            ReconciledRoute::Repairing => RunState::Repairing,
        }
    }

    /// Whether this route needs a human before the run can move again (§4.8).
    pub fn requires_human(&self) -> bool {
        matches!(
            self,
            ReconciledRoute::AwaitingApproval
                | ReconciledRoute::AwaitingReview
                | ReconciledRoute::Blocked
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_state_has_twelve_variants() {
        assert_eq!(TaskState::ALL.len(), 12);
    }

    #[test]
    fn run_state_covers_the_claim_predicate() {
        // S1 asserted RECOVERING here, pinning the contradiction §4.7 recorded.
        // S3 resolved it: the claim selects READY and RECONCILING, and every
        // member of the predicate must be a state something can actually write.
        assert_eq!(RunState::Ready.as_str(), "READY");
        assert_eq!(RunState::Reconciling.as_str(), "RECONCILING");
        assert_eq!(RunState::Running.as_str(), "RUNNING");
        assert_eq!(
            RunState::CLAIMABLE,
            &[RunState::Ready, RunState::Reconciling]
        );
    }

    #[test]
    fn recovering_is_not_a_run_state() {
        // The dead disjunct is gone, and it must stay gone: parsing it is an
        // error rather than a silently accepted legacy value.
        assert!("RECOVERING".parse::<RunState>().is_err());
        assert!(!RunState::ALL.iter().any(|s| s.as_str() == "RECOVERING"));
    }

    #[test]
    fn the_run_state_mirrors_its_task_variant_for_variant() {
        // §5.2: "Deliberately thin — mirrors its task." Two enums that are meant
        // to be the same set are two things that can drift, so the agreement is
        // asserted rather than assumed.
        let run: Vec<&str> = RunState::ALL.iter().map(|s| s.as_str()).collect();
        let task: Vec<&str> = TaskState::ALL.iter().map(|s| s.as_str()).collect();
        assert_eq!(run, task);
    }

    #[test]
    fn no_route_out_of_reconciliation_reaches_complete() {
        // The type has no COMPLETE variant; this pins the consequence, which is
        // that nothing reachable from reconciliation writes a terminal state.
        for route in [
            ReconciledRoute::Verifying,
            ReconciledRoute::AwaitingApproval,
            ReconciledRoute::AwaitingReview,
            ReconciledRoute::Blocked,
            ReconciledRoute::Repairing,
        ] {
            assert!(
                !route.state().is_terminal(),
                "{route:?} routes to a terminal state"
            );
        }
    }

    #[test]
    fn text_round_trips_for_every_variant() {
        for s in TaskState::ALL {
            assert_eq!(&s.as_str().parse::<TaskState>().expect("parse"), s);
        }
        for s in RunState::ALL {
            assert_eq!(&s.as_str().parse::<RunState>().expect("parse"), s);
        }
        for s in PlanVersionState::ALL {
            assert_eq!(&s.as_str().parse::<PlanVersionState>().expect("parse"), s);
        }
        for s in AttemptOutcome::ALL {
            assert_eq!(&s.as_str().parse::<AttemptOutcome>().expect("parse"), s);
        }
    }

    #[test]
    fn serde_agrees_with_the_persisted_text() {
        // Two encodings of the same thing must not be allowed to drift: the
        // database sees as_str(), a JSON packet sees serde.
        for s in RunState::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
        for s in TaskState::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
        for s in AttemptOutcome::ALL {
            let json = serde_json::to_string(s).expect("serialize");
            assert_eq!(json, format!("\"{}\"", s.as_str()));
        }
    }

    #[test]
    fn unknown_state_is_rejected_not_defaulted() {
        let err = "NOT_A_STATE".parse::<RunState>().unwrap_err();
        assert_eq!(err.type_name, "RunState");
        assert_eq!(err.value, "NOT_A_STATE");
    }

    #[test]
    fn terminal_sets_match_the_partial_index_predicate() {
        let terminal: Vec<&str> = RunState::ALL
            .iter()
            .filter(|s| s.is_terminal())
            .map(|s| s.as_str())
            .collect();
        assert_eq!(terminal, vec!["COMPLETE", "CANCELLED", "SUPERSEDED"]);
        assert!(RunState::Running.occupies_active_slot());
        assert!(!RunState::Complete.occupies_active_slot());
    }
}
