//! The verification outcome set — master plan §4.5.
//!
//! # Why this type lives in `conductor-core`
//!
//! S2 defined it in `conductor-git`, next to the `reconcile()` that takes it as
//! evidence, and that was right while it was only evidence. S4 makes it a
//! persisted value: `verification_check.outcome` is a `TEXT` column whose four
//! legal strings this enum decides, and `conductor-store` cannot depend on
//! `conductor-git` (§2.3 puts the store below the git provider, and the two are
//! siblings, not a stack). A pure enum with no I/O is exactly what §2.3 puts in
//! `conductor-core`; it is re-exported from `conductor-git` so the S2 call sites
//! are unaffected.
//!
//! It is generated by the same `state_enum!` macro as every other state column,
//! for the reason that macro exists: the database's encoding and serde's must
//! not be free to drift apart.

use crate::state::state_enum;

state_enum! {
    /// `verification_check.outcome` — §4.5's four outcomes.
    ///
    /// **`INCONCLUSIVE` is not a failure**, and the distinction is the reason
    /// there are four of these rather than three. §4.5: "`FAIL` → repair;
    /// `INCONCLUSIVE` → bounded infra retry, then human. Collapsing them is how
    /// a broken cache turns into three wasted agent attempts."
    ///
    /// **`VOID` is not a result at all.** It says the tree moved under the
    /// check, so the run observed a tree that never existed as a whole. §4.5:
    /// "a result whose tree moved under it is `VOID`, not `PASS`."
    VerificationOutcome {
        Pass => "PASS",
        Fail => "FAIL",
        Inconclusive => "INCONCLUSIVE",
        Void => "VOID",
    }
    terminal: []
}

impl VerificationOutcome {
    /// Whether this outcome may be served from the content-addressed cache.
    ///
    /// Exactly the predicate of Part 5.1's partial index:
    /// `WHERE outcome IN ('PASS','FAIL')`. The other two are deliberately
    /// uncacheable — see the module docs on `conductor_store::verification`.
    pub fn is_cacheable(&self) -> bool {
        matches!(self, VerificationOutcome::Pass | VerificationOutcome::Fail)
    }

    /// Whether this outcome permits a task to reach `COMPLETE` (§4.5).
    pub fn is_pass(&self) -> bool {
        matches!(self, VerificationOutcome::Pass)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_four_outcomes_are_exactly_the_ones_part_5_1_documents() {
        let all: Vec<&str> = VerificationOutcome::ALL
            .iter()
            .map(|o| o.as_str())
            .collect();
        assert_eq!(all, ["PASS", "FAIL", "INCONCLUSIVE", "VOID"]);
    }

    #[test]
    fn only_pass_and_fail_are_cacheable() {
        // Mirrors `ix_verif_cache`'s partial predicate. If this ever disagrees
        // with the DDL, the cache silently starts serving results that describe
        // a moment rather than a tree.
        assert!(VerificationOutcome::Pass.is_cacheable());
        assert!(VerificationOutcome::Fail.is_cacheable());
        assert!(!VerificationOutcome::Inconclusive.is_cacheable());
        assert!(!VerificationOutcome::Void.is_cacheable());
    }

    #[test]
    fn inconclusive_is_not_a_pass_and_not_a_failure() {
        assert!(!VerificationOutcome::Inconclusive.is_pass());
        assert!(!VerificationOutcome::Void.is_pass());
        assert!(VerificationOutcome::Pass.is_pass());
    }

    #[test]
    fn serde_agrees_with_the_persisted_text() {
        for outcome in VerificationOutcome::ALL {
            let json = serde_json::to_string(outcome).expect("serialize");
            assert_eq!(json, format!("\"{}\"", outcome.as_str()));
            assert_eq!(
                &outcome
                    .as_str()
                    .parse::<VerificationOutcome>()
                    .expect("parse"),
                outcome
            );
        }
    }
}
